export const routes = {
  auth: "/auth",
  onboarding: "/onboarding",
  typeTest: "/test",
  typeResult: "/test/result",
  program: "/program",
  together: "/together",
  library: "/library",
  profile: "/profile",
  person: "/people",
  birth: "/birth",
  elementResult: "/element-result",
  admin: "/admin",
  adminMaterials: "/admin/materials",
  adminProgram: "/admin/program",
  adminSupport: "/admin/support",
  adminStudents: "/admin/students",
} as const;
